version: '3'
services:
    server:
        build:
            context: server
            dockerfile: Dockerfile
        ports:
            - "50051:50051"
    client:
        build:
            context: client
            dockerfile: Dockerfile
        depends_on:
            - "server"
        command: ["./wait-for-it.sh", "server:50051", "--", "python", "client.py"]
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    weblogs:
        build:
            context: web-dashboard
            dockerfile: Dockerfile
        ports:
            - "8080:5000"
        depends_on:
            - "redis"
