apiVersion: v1
kind: Service
metadata:
    labels:
        app: weblogs
    name: weblogs
spec:
    selector:
        app: a02-web-dashboard
    type: NodePort
    ports:
    - port: 5000
      nodePort: 30000
      protocol: TCP
