apiVersion: v1
kind: Service
metadata:
    name: weblogs
    labels:
        app: weblogs
spec:
    ports:
    - port: 50051
      protocol: TCP
    selector:
        app: weblogs
    type: NodePort
    ports:
    - port: 5000
      nodePort: 30000
      protocol: TCP
