# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import reddit_simulation_pb2 as reddit__simulation__pb2


class DataStreamingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartDatastream = channel.unary_stream(
                '/DataStreamingService/StartDatastream',
                request_serializer=reddit__simulation__pb2.Request.SerializeToString,
                response_deserializer=reddit__simulation__pb2.Response.FromString,
                )


class DataStreamingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartDatastream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataStreamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartDatastream': grpc.unary_stream_rpc_method_handler(
                    servicer.StartDatastream,
                    request_deserializer=reddit__simulation__pb2.Request.FromString,
                    response_serializer=reddit__simulation__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataStreamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataStreamingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartDatastream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/DataStreamingService/StartDatastream',
            reddit__simulation__pb2.Request.SerializeToString,
            reddit__simulation__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
