apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: a02-server
    minReadySeconds: 6
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
                app: a02-server
        spec:
            containers:
            - name: a02-server
              image: zacdair/a02-server:latest
              ports:
              - containerPort: 50051
                
