apiVersion: apps/v1
kind: Deployment
metadata:
    name: weblogs-deploy
spec:
    replicas: 4
    selector:
        matchLabels:
            app: a02-web-dashboard
    minReadySeconds: 10
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
                app: a02-web-dashboard
        spec:
            containers:
            - name: a02-web-dashboard
              image: zacdair/a02-web-dashboard:latest
              ports:
              - containerPort: 5000
                
